SELECT * FROM Tabela

--1
SELECT
	*
FROM Tabela
WHERE Nome LIKE '[Mm]_[Rr]%'

--2
SELECT
	*
FROM Tabela
WHERE Nome LIKE '[A-z]_[A-z]%'


--RETORNAR NOMES QUE N TEM CERTA LETRA 
SELECT 
	*
FROM Tabela
WHERE Nome LIKE '[^Ll]%'

--RETORNAR NOME COM A PRIMEIRA LETRA QUALQUER UMA MAS QUE A SEGUNDA NAO TENHA A 'E'
SELECT
	*
FROM Tabela
WHERE Nome LIKE '_[^Ee]%'


--RETORNAR APENAS CARACTERES ESPECIAIAS 
SELECT
	*
FROM Textos
WHERE Texto LIKE '[^A-Z0-9]%'