SELECT * FROM DimProduct
SET NOCOUNT ON


DECLARE @VARON INT = (SELECT COUNT(*) FROM DimStore WHERE Status = 'On'),
		@VAROFF INT = (SELECT COUNT(*) FROM DimStore WHERE Status = 'Off')

SELECT @VARON AS 'ON', @VAROFF AS 'OFF'

PRINT 'O TOTAL DE LOJAS ABERTAS É DE ' + CAST(@VARON AS VARCHAR(20))
PRINT @VAROFF